# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Vasco Flores
tagline:          'Página pessoal'
description:      'Computer tamer'
url:              http://vxf.github.io
baseurl:          /

author:
  name:           'Vasco Flores'
  url:            https://vxf.github.io/

# paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vxf/vxf.github.io
